export const SET_USER_DATA = 'SET_USER_DATA'
export const DELETE_USER_DATA = 'DELETE_USER_DATA'

export const SET_COMPANY_DATA = 'SET_COMPANY_DATA'
export const DELETE_COMPANY_DATA = 'DELETE_COMPANY_DATA'
