export { default as AverageCustomerRatingTab } from './AverageCustomerRatingTab'
export { default as DashboardTabBar } from './DashboardTabBar'
export { default as NumberOfReturnsTab } from './NumberOfReturnsTab'
export { default as NumberOfServicesTab } from './NumberOfServicesTab'
export { default as OverviewTab } from './OverviewTab'
export { default as withDashboardContext } from './withDashboardContext'
