export default {
  TODAY: '@DT/DATA_HOJE',
  CURRENT_DAY: '@DT/DIA_HOJE',
  CURRENT_MONTH: '@DT/MES_ATUAL',
  CURRENT_YEAR: '@DT/ANO_ATUAL',

  COMPANY_FANTASY_NAME: '@EMP/FANTASIA',
  COMPANY_CNPJ: '@EMP/CNPJ',
  COMPANY_NAME: '@EMP/NOME',
  COMPANY_OWNER_NAME: '@EMP/NOME_DONO',
  COMPANY_OWNER_PHONE: '@EMP/CEL_DONO',
  COMPANY_EMAIL: '@EMP/EMAIL_DONO',

  CUSTOMER_BIRTH_DATE: '@CLI/DATA_NASCIMENTO',
  CUSTOMER_NAME: '@CLI/NOME',
  CUSTOMER_WHATSAPP: '@CLI/WHATSAPP',
  CUSTOMER_BIRTH_DAY: '@CLI/DIA_NASCIMENTO',
  CUSTOMER_BIRTH_MONTH: '@CLI/MES_NASCIMENTO',
  CUSTOMER_BIRTH_YEAR: '@CLI/ANO_NASCIMENTO',
  CUSTOMER_PHONE: '@CLI/CELULAR',
  CUSTOMER_EMAIL: '@CLI/EMAIL',
  CUSTOMER_CEP: '@CLI/CEP',
  CUSTOMER_CITY: '@CLI/CIDADE',
  CUSTOMER_STATE: '@CLI/ESTADO',
  CUSTOMER_DISTRICT: '@CLI/BAIRRO',
  CUSTOMER_ADDRESS: '@CLI/ENDERECO',
  CUSTOMER_NUMBER: '@CLI/NUMERO',
  CUSTOMER_COMPLEMENT: '@CLI/COMPLEMENTO',

  USER_NAME: '@USR/NOME',

  SERVICE_TYPE_NAME: '@TPS/NOME',
  SERVICE_TYPE_DESCRIPTION: '@TPS/DESCRICAO',

  SERVICE_START_DATE: '@SRV/DATA_INICIO',
  SERVICE_END_DATE: '@SRV/DATA_TERMINO',
}
