export default {
  TODAY: '@DT/DATA_HOJE',
  CURRENT_DAY: '@DT/DIA_HOJE',
  CURRENT_MONTH: '@DT/MES_ATUAL',
  CURRENT_YEAR: '@DT/ANO_ATUAL',

  COMPANY_FANTASY_NAME: '@EMP/FANTASIA',
  COMPANY_CNPJ: '@EMP/CNPJ',
  COMPANY_NAME: '@EMP/NOME',
  COMPANY_OWNER_NAME: '@EMP/NOME_DONO',
  COMPANY_OWNER_PHONE: '@EMP/CEL_DONO',
  COMPANY_EMAIL: '@EMP/EMAIL_DONO',

  CUSTOMER_BIRTH_DATE: '@CLI/_DATA_NASCIMENTO',
  CUSTOMER_NAME: '@CLI/_NOME',
  CUSTOMER_WHATSAPP: '@CLI/_WHATSAPP',
  CUSTOMER_BIRTH_DAY: '@CLI/_DIA_NASCIMENTO',
  CUSTOMER_BIRTH_MONTH: '@CLI/_MES_NASCIMENTO',
  CUSTOMER_BIRTH_YEAR: '@CLI/_ANO_NASCIMENTO',
  CUSTOMER_PHONE: '@CLI/_CELULAR',
  CUSTOMER_EMAIL: '@CLI/_EMAIL',
  CUSTOMER_CEP: '@CLI/_CEP',
  CUSTOMER_CITY: '@CLI/_CIDADE',
  CUSTOMER_STATE: '@CLI/_ESTADO',
  CUSTOMER_DISTRICT: '@CLI/_BAIRRO',
  CUSTOMER_ADDRESS: '@CLI/_ENDERECO',
  CUSTOMER_NUMBER: '@CLI/_NUMERO',
  CUSTOMER_COMPLEMENT: '@CLI/_COMPLEMENTO',

  USER_NAME: '@USR/NOME',

  SERVICE_TYPE_NAME: '@TPS/NOME',
  SERVICE_TYPE_DESCRIPTION: '@TPS/DESCRICAO',

  SERVICE_START_DATE: '@SRV/DATA_INICIO',
  SERVICE_END_DATE: '@SRV/DATA_TERMINO',
}
