export default {
  ID: 'customerId',
  NAME: 'name',
  WHATSAPP: 'whatsapp',
  BIRTH_DATE: 'birthDate',
  PHONE: 'phone',
  EMAIL: 'email',
  CEP: 'cep',
  CITY: 'city',
  STATE: 'state',
  DISTRICT: 'district',
  ADDRESS: 'address',
  NUMBER: 'number',
  COMPLEMENT: 'complement',
  CREATED_AT: 'createdAt',
  CAN_RECEIVE_MESSAGES: 'canReceiveMessages',
}
