export const RATE_SERVICE_PARAMS = {
  IS_EDITING: 'IS_EDITING',
  CURRENT_NOTE: 'CURRENT_NOTE',
  CURRENT_COMMENT: 'CURRENT_COMMENT',
}

export const CUSTOMER_RETURN_REGISTRATION_PARAMS = {
  IS_EDITING: 'IS_EDITING',
}

export const RETURN_REASON_PARAMS = {
  IS_STACK_PAGE: 'IS_STACK_PAGE',
}

export const EDIT_USER_NAME_PARAMS = {
  USER_NAME: 'USER_NAME',
  USER_ID: 'USER_ID',
}

export const EDIT_USER_EMAIL_PARAMS = {
  USER_EMAIL: 'USER_EMAIL',
}

export const DASHBOARD_FILTERS_PARAMS = {
  CURRENT_FILTERS: 'CURRENT_FILTERS',
  ON_FILTER: 'ON_FILTER',
}

export const FORGOT_PASSWORD_PARAMS = {
  LOGIN_EMAIL: 'LOGIN_EMAIL',
}

export const EDIT_SERVICE_PARAMS = {
  SERVICE_DATA: 'SERVICE_DATA',
}
