export const RATE_SERVICE_PARAMS = {
  IS_EDITING: 'IS_EDITING',
  CURRENT_NOTE: 'CURRENT_NOTE',
  CURRENT_COMMENT: 'CURRENT_COMMENT',
}

export const CUSTOMER_RETURN_REGISTRATION_PARAMS = {
  IS_EDITING: 'IS_EDITING',
}

export const RETURN_REASON_PARAMS = {
  IS_STACK_PAGE: 'IS_STACK_PAGE',
}

export const EDIT_USER_NAME_PARAMS = {
  USER_NAME: 'USER_NAME',
  USER_ID: 'USER_ID',
}
