export const RATE_SERVICE_PARAMS = {
  IS_EDITING: 'IS_EDITING',
  CURRENT_NOTE: 'CURRENT_NOTE',
  CURRENT_COMMENT: 'CURRENT_COMMENT',
}

export const CUSTOMER_RETURN_REGISTRATION_PARAMS = {
  IS_EDITING: 'IS_EDITING',
}
