export const DRAWER_ROUTES = {
  HOME: '@DRAWER/HOME',
  DASHBOARD: '@DRAWER/DASHBOARD',
  MARKETING_STEP_REGISTRATION: '@DRAWER/MARKETING_STEP_REGISTRATION',
  SERVICE_TYPE_REGISTRATION: '@DRAWER/SERVICE_TYPE_REGISTRATION',
  CUSTOMER_REGISTRATION: '@DRAWER/CUSTOMER_REGISTRATION',
  SERVICE_REGISTRATION: '@DRAWER/SERVICE_REGISTRATION',
  SERVICE_TYPE_LIST: '@DRAWER/SERVICE_TYPE_LIST',
  CUSTOMER_LIST: '@DRAWER/CUSTOMER_LIST',
  SERVICE_LIST: '@DRAWER/SERVICE_LIST',
  MARKETING_STEP_LIST: '@DRAWER/MARKETING_STEP_LIST',
  USER_PROFILE: '@DRAWER/USER_PROFILE',
  RETURN_REASON_REGISTRATION: '@DRAWER/RETURN_REASON_REGISTRATION_DRAWER',
  RETURN_REASON_LIST: '@DRAWER/RETURN_REASON_LIST',
  BIRTHDAY_MESSAGES_CONFIG: '@DRAWER/BIRTHDAY_MESSAGES_CONFIG',
}

export const MAIN_ROUTES = {
  CUSTOMER_DETAILS: '@MAIN/CUSTOMER_DETAILS',
  SERVICE_DETAILS: '@MAIN/SERVICE_DETAILS',
  MARKETING_STEP_DETAILS: '@MAIN/MARKETING_STEP_DETAILS',
  RATE_SERVICE: '@MAIN/RATE_SERVICE',
  CUSTOMER_RETURN_REGISTRATION: '@MAIN/CUSTOMER_RETURN_REGISTRATION',
  RETURN_REASON_REGISTRATION: '@MAIN/RETURN_REASON_REGISTRATION_STACK',
  USER_SECURITY: '@MAIN/USER_SECURITY',
  USER_PERSONAL_DATA: '@MAIN/USER_PERSONAL_DATA',
  CHANGE_PASSWORD: '@MAIN/CHANGE_PASSWORD',
  EDIT_USER_NAME: '@MAIN/EDIT_USER_NAME',
  EDIT_USER_EMAIL: '@MAIN/EDIT_USER_EMAIL',
  DASHBOARD_FILTERS: '@MAIN/DASHBOARD_FILTERS',
  EDIT_SERVICE: '@MAIN/EDIT_SERVICE',
  EDIT_MARKETING_STEP: '@MAIN/EDIT_MARKETING_STEP',
  EDIT_CUSTOMER: '@MAIN/EDIT_CUSTOMER',
}

export const SERVICE_DETAILS_ROUTES = {
  OVERVIEW_TAB: '@SERVICE_DETAILS/OVERVIEW_TAB',
  SEND_MESSAGES_TAB: '@SERVICE_DETAILS/SEND_MESSAGES_TAB',
  CUSTOMER_RATING_TAB: '@SERVICE_DETAILS/CUSTOMER_RATING_TAB',
  CUSTOMER_RETURN_TAB: '@SERVICE_DETAILS/CUSTOMER_RETURN_TAB',
}

export const APP_SWITCH_ROUTES = {
  AUTH_LOADING: '@APP/AUTH_LOADING',
}

export const NAVIGATOR_ROUTES = {
  DRAWER_NAVIGATOR: '@NAVIGATOR/DRAWER_NAVIGATOR',
  MAIN_NAVIGATOR: '@NAVIGATOR/MAIN_NAVIGATOR',
  LOGIN_NAVIGATOR: '@NAVIGATOR/LOGIN_NAVIGATOR',
}

export const DASHBOARD_ROUTES = {
  DASHBOARD_OVERVIEW_TAB: '@DASHBOARD/DASHBOARD_OVERVIEW_TAB',
  NUM_OF_SERVICES_TAB: '@DASHBOARD/NUM_OF_SERVICES_TAB',
  NUM_OF_RETURNS_TAB: '@DASHBOARD/NUM_OF_RETURNS_TAB',
  AVERAGE_CUSTOMER_RATING_TAB: '@DASHBOARD/AVERAGE_CUSTOMER_RATING_TAB',
}

export const LOGIN_ROUTES = {
  LOGIN: '@LOGIN/LOGIN',
  FORGOT_PASSWORD: '@LOGIN/FORGOT_PASSWORD',
  COMPANY_REGISTRATION: '@LOGIN/COMPANY_REGISTRATION',
}
