export const DRAWER_ROUTES = {
  HOME: 'HOME',
  DASHBOARD: 'DASHBOARD',
  MARKETING_STEP_REGISTRATION: 'MARKETING_STEP_REGISTRATION',
  SERVICE_TYPE_REGISTRATION: 'SERVICE_TYPE_REGISTRATION',
  CUSTOMER_REGISTRATION: 'CUSTOMER_REGISTRATION',
  SERVICE_REGISTRATION: 'SERVICE_REGISTRATION',
  SERVICE_TYPES_LIST: 'SERVICE_TYPES_LIST',
  CUSTOMERS_LIST: 'CUSTOMERS_LIST',
  SERVICES_LIST: 'SERVICES_LIST',
}

export const MAIN_ROUTES = {
  CUSTOMER_DETAILS: 'CUSTOMER_DETAILS',
  SERVICE_DETAILS: 'SERVICE_DETAILS',
}

export const APP_SWITCH_ROUTES = {
  AUTH_LOADING: 'AUTH_LOADING',
  LOGIN: 'LOGIN',
}

export const NAVIGATOR_ROUTES = {
  DRAWER_NAVIGATOR: 'DRAWER_NAVIGATOR',
  MAIN_NAVIGATOR: 'MAIN_NAVIGATOR',
}
