export const DRAWER_ROUTES = {
  HOME: 'HOME',
  DASHBOARD: 'DASHBOARD',
  MARKETING_STEP_REGISTRATION: 'MARKETING_STEP_REGISTRATION',
  SERVICE_TYPE_REGISTRATION: 'SERVICE_TYPE_REGISTRATION',
  CUSTOMER_REGISTRATION: 'CUSTOMER_REGISTRATION',
  SERVICE_REGISTRATION: 'SERVICE_REGISTRATION',
  SERVICE_TYPE_LIST: 'SERVICE_TYPE_LIST',
  CUSTOMER_LIST: 'CUSTOMER_LIST',
  SERVICE_LIST: 'SERVICE_LIST',
  MARKETING_STEP_LIST: 'MARKETING_STEP_LIST',
  USER_PROFILE: 'USER_PROFILE',
}

export const MAIN_ROUTES = {
  CUSTOMER_DETAILS: 'CUSTOMER_DETAILS',
  SERVICE_DETAILS: 'SERVICE_DETAILS',
  MARKETING_STEP_DETAILS: 'MARKETING_STEP_DETAILS',
}

export const APP_SWITCH_ROUTES = {
  AUTH_LOADING: 'AUTH_LOADING',
  LOGIN: 'LOGIN',
}

export const NAVIGATOR_ROUTES = {
  DRAWER_NAVIGATOR: 'DRAWER_NAVIGATOR',
  MAIN_NAVIGATOR: 'MAIN_NAVIGATOR',
}
